"""Domain adapter registry for curriculum data collection."""

from .base import (
    GENERATOR_DUPLICATE_OUTPUT_REASON,
    GENERATOR_FAILED_REASON,
    GENERATOR_MISSING_DOMAIN_REASON,
    GENERATOR_MISSING_OUTPUT_REASON,
    GENERATOR_TIMEOUT_REASON,
    INVALID_PDDL_REASON,
    GenerationSpec,
    GeneratorAdapter,
    GeneratorRejection,
    GeneratorRunResult,
    NormalizedCandidate,
)
from .registry import (
    AdapterCapability,
    AdapterMetadata,
    AdapterReadinessFailure,
    CurriculumCommandAdapter,
    DomainSelection,
    PreparedCommand,
    ProblemOutputPolicy,
    SeedPolicy,
    TargetParameterPreset,
    build_adapter_capability_matrix,
    build_domain_adapter,
    build_domain_registry,
    registry_domain_ids,
)

__all__ = [
    "AdapterCapability",
    "AdapterMetadata",
    "AdapterReadinessFailure",
    "CurriculumCommandAdapter",
    "DomainSelection",
    "GENERATOR_DUPLICATE_OUTPUT_REASON",
    "GENERATOR_FAILED_REASON",
    "GENERATOR_MISSING_DOMAIN_REASON",
    "GENERATOR_MISSING_OUTPUT_REASON",
    "GENERATOR_TIMEOUT_REASON",
    "GenerationSpec",
    "GeneratorAdapter",
    "GeneratorRejection",
    "GeneratorRunResult",
    "INVALID_PDDL_REASON",
    "NormalizedCandidate",
    "PreparedCommand",
    "ProblemOutputPolicy",
    "SeedPolicy",
    "TargetParameterPreset",
    "build_adapter_capability_matrix",
    "build_domain_adapter",
    "build_domain_registry",
    "registry_domain_ids",
]
